package org.paninij.apt.util;

import java.util.ArrayList;
import java.util.List;

import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.util.Types;

import org.paninij.apt.PaniniPress;


/**
 * Note that a duck shape has a void return type if and only if `returnType` is set to `null`.
 */
public class DuckShape
{
    public final DeclaredType returnType;
    public final List<String> parameters;
    private final Types typeUtils;

    public static DuckShape make(PaniniPress context, ExecutableElement method)
    {
        DeclaredType returnType;
        if (ModelInfo.hasVoidReturnType(method))
        {
            returnType = null;
        }
        else
        {
            returnType = (DeclaredType) method.getReturnType();
        }

        List<String> params = new ArrayList<String>();
        for (VariableElement param : method.getParameters())
        {
            params.add(param.asType().toString());
        }

        return new DuckShape(returnType, params, context.getTypeUtils());
    }


    public DuckShape(DeclaredType returnType, List<String> parameters, Types typeUtils)
    {
        // The `typeUtils` argument is required in order to implement `equals()` correctly.
        this.returnType = returnType;
        this.parameters = parameters;
        this.typeUtils = typeUtils;
    }


    @Override
    public int hashCode()
    {
        // This implementation auto-generated by Eclipse.
        final int prime = 31;
        int result = 1;
        result = prime * result + ((parameters == null) ? 0 : parameters.hashCode());
        result = prime * result + ((returnType == null) ? 0 : returnType.hashCode());
        return result;
    }


    @Override
    public boolean equals(Object obj)
    {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }

        DuckShape other = (DuckShape) obj;
        if (parameters == null)
        {
            if (other.parameters != null) {
                return false;
            }
        }
        else if (!parameters.equals(other.parameters))
        {
            return false;
        }

        if (returnType == null)
        {
            if (other.returnType != null) {
                return false;
            }
        }
        else if (!typeUtils.isSameType(returnType, other.returnType))
        {
            return false;
        }
        return true;
    }


    public String toString()
    {
        String ret = getSimpleReturnType() + "$Duck";
        
        if(parameters.size() == 0)
        {
            ret += "$void";
        }
        else
        {
            for(String param : parameters)
            {
                ret += "$" + Source.dropPackageName(param);
            }
        }
        
        return ret;
    }

    
    /**
     * Returns the name of the return type associated with the duck shape. If there is no return
     * type (i.e. `returnType == null`) then "void" is returned.
     */
    public String getSimpleReturnType()
    {
        if (returnType == null) {
            return "void";
        } else {
            return Source.dropPackageName(returnType.toString());
        }
    }
    
    /**
     * Returns the fully qualified name of the return type associated with the duck shape. If there
     * is no return type (i.e. `returnType == null`) then "void" is returned.
     */
    public String getQualifiedReturnType()
    {
        if (returnType == null) {
            return "void";
        } else {
            return returnType.toString();
        }
    }
    

    public enum Category
    {
        NORMAL,
        VOID,
        FINAL,
        ARRAY,
        FINALARRAY,
        PRIMITIVE,
        PANINICUSTOM
    }
    

    public static DuckShape.Category categoryOf(DuckShape duckShape)
    {
        // TODO: Add checks for all categories
        if (duckShape.returnType == null)
        {
            return Category.VOID;
        }
        else if (ModelInfo.isFinalType(duckShape.returnType))
        {
            return Category.FINAL;
        }
        else
        {
            return Category.NORMAL;
        }

    }
}
